apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: node-taint-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Currently only removes the "kubernetes.io/arch" taint from newly added
    nodes.
  displayName: Node Taint Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - node
  - taint
  - remover
  - arm64
  links:
  - name: Node Taint Operator
    url: https://node-taint-operator.domain
  maintainers:
  - email: briankanya@gmail.com
    name: Brian Kanya
  maturity: alpha
  provider:
    name: node-taint-operator
    url: https://github.com/kanya-approve/node-taint-operator
  version: 0.0.0
