name: Test

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions: read-all

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Run integration tests
        run: make test
